init repo
elixir-cloud-aai/trs-filer pull request #2
Opened 2020-07-06 23:38 UTC by kushagra189

Repo initialization.

2020-07-07 12:05 UTC, uniqueg requested changes
Looking mostly alright, but a couple of minor suggestions. Partly relevant for @sarthakgupta072, too

2020-07-07 12:05 UTC, uniqueg commented on .travis.yml
> +  # - coverage run --source drs-filer -m pytest
Please either uncomment these OR delete these for now

2020-07-07 12:05 UTC, uniqueg commented on Dockerfile
> +##### BASE IMAGE #####
Make sure to use the FOCA Dockerfile as base image, as this will speed up your builds. Make sure to only include here what you really need for DRS-filer.

Also, have a look at the FOCA Dockerfile and keep only those metadata LABELs that we have in FOCA. I cleaned them up recently, I think many, if not most, of them were pointless/confusing, and hard to maintain.

2020-07-07 12:05 UTC, uniqueg commented on LICENSE
> -   limitations under the License.
Not sure what the difference here is or why it's needed. Is there some additional whitespace?

2020-07-07 12:05 UTC, uniqueg commented on docker-compose.yaml
> +# TODO: Specify the services here. Refer cwl-wes
I suppose you can leave this out for now and add it once you have it completed. You can have a look at DRS-filer (https://github.com/elixir-cloud-aai/drs-filer/pull/5/files) to see how it should look like more or less

2020-07-07 12:05 UTC, uniqueg commented on requirements.txt
> +coverage==5.0.3
Please check whether you really need all of these packages. Only add what you explicitly import from. If packages are installed as dependencies of another module that you need explicitly, don't mention them here, because the version lock may cause unnecessary problems if you update dependencies.

2020-07-07 12:05 UTC, uniqueg commented on setup.py
> +    version='0.1.0',
Compare https://github.com/elixir-cloud-aai/foca/blob/dev/setup.py to see how we can define the version without hardcoding it in the setup file.

Basically, you need to:
- add `__version__ = '0.1.0'` to `trs_filer/__init__.py` (this should be the _single_ place in the repo where the version is hard-coded)
- add `from trs_filer import __version__` to the import section of `setup.py`
- write `version=__version__` in the `setup()` function

@sarthakgupta072: this goes for DRS-filer, too.

2020-07-07 12:05 UTC, uniqueg commented on setup.py
> +        'ga4gh drs elixir rest restful api app server openapi '
replace `drs` with `trs`

2020-07-07 12:05 UTC, uniqueg commented on setup.py
> +        'Programming Language :: Python :: 3.5',
I think we should remove `3.5`, it doesn't even have f-strings, I think.

@sarthakgupta072: same for DRS-filer

2020-07-07 12:05 UTC, uniqueg commented on setup.py
> +    install_requires=['connexion', 'Flask-Cors', 'Flask-PyMongo'],
I don't think any of these are required by default. Only add what you really import anywhere.

@sarthakgupta072: goes for DRS-filer, too

2020-07-07 12:05 UTC, uniqueg commented on README.md
>  # trs-filer
Should be TRS-filer when not referring to the PyPI package etc.

@sarthakgupta072: goes for DRS-filer, too

2020-07-07 12:05 UTC, uniqueg commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] I have not reduced the existing code coverage
Add:

- [ ] I have added docstrings following the [Python style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/python.md) of this project to all new modules, classes, methods and functions are documented with docstrings following; I have updated any previously existing docstrings, if applicable
- [ ] I have updated any sections of the app's documentation that are affected by the proposed changes, if applicable

@sarthakgupta072 goes for DRS-filer, too

2020-07-08 02:28 UTC, kushagra189 commented on setup.py
> +    version='0.1.0',
@uniqueg  I was facing some issues while doing this, keeping it on a TODO for now.

2020-07-12 15:49 UTC, uniqueg requested changes
Some minor issues, almost there. :)

2020-07-12 15:49 UTC, uniqueg commented on Dockerfile
> +##### BASE IMAGE #####
Still there are some labels that shouldn't be in there. Please use _only_ these labels (copied from FOCA `Dockerfile` so values are of course different):

```Dockerfile
LABEL software="FOCA"
LABEL software.description="Kickstart OpenAPI-based microservice development with Flask & Connexion"
LABEL software.website="https://github.com/elixir-cloud-aai/foca"
LABEL software.license="https://spdx.org/licenses/Apache-2.0"
LABEL maintainer="alexander.kanitz@alumni.ethz.ch"
LABEL maintainer.organisation="ELIXIR Cloud & AAI"
```

And make sure to add some value to `software.description`.

2020-07-12 15:49 UTC, uniqueg commented on Dockerfile
> +
Leave only a single empty line

2020-07-12 15:49 UTC, uniqueg commented on LICENSE
> -   limitations under the License.
Now it looks like the file was deleted? Please re-include it.

2020-07-12 15:49 UTC, uniqueg commented on setup.py
> +        'Programming Language :: Python :: 3.6',
Well, we are testing against `3.7` and `3.8`, so I think you can include these as well - Python 3.6 is pretty old...

2020-07-13 08:49 UTC, uniqueg approved these changes
Great, thanks!

2020-07-13 08:53 UTC, merged